const constantes = {
    ACCION : 'Acción',
    CANCELAR : 'Cancelar',
    CANTIDAD : 'Cantidad',
    CANTIDAD_INCORRECTA : 'La cantidad del producto es incorrecta',
    CLIENTE : 'Cliente', 
    CLIENTE_INEXISTENTE : 'El cliente especificado no existe',
    CLIENTE_SIN_ESPECIFICAR : 'No se especifó un cliente',
    CLIENTE_ACTUALIZADO : 'Cliente actualizado',
    ERROR_ACTUALIZAR_CLIENTE : 'Error al actualizar el cliente',
    ERROR_ACTUALIZAR_INGREDIENTES : 'Error al actualizar los ingredientes',
    ERROR_ACTUALIZAR_PEDIDO : 'Error al actualizar el pedido',
    ERROR_ACTUALIZAR_PRODUCTO : 'Error al actualizar el producto',
    ERROR_GUARDAR_PEDIDO : 'Error al guardar el pedido',
    ERROR_OBTENER_EQUIVALENCIA : 'Error al obtener la equivalencia',
    ERROR_LEER_CLIENTES_PRODUCTOS : 'Error al leer los clientes y/o productos',  
    ERROR_LEER_INGREDIENTES : 'Error al leer los ingredientes',    
    ERROR_LEER_PEDIDOS : 'Error al leer los pedidos',    
    ESTADO : 'Estado',
    ESTADO_ELABORACION : 'En elaboración',
    ESTADO_ENTREGADO : 'Entregado',   
    ESTADO_PEDIDO : 'Pedido',
    ESTADO_TERMINADO : 'Terminado',
    FECHA : 'Fecha',
    IMPORTE : 'Importe',
    INGREDIENTES_ACTUALIZADOS : 'Ingredientes actualizados',
    NUEVO_PEDIDO : 'Nuevo Pedido',
    PEDIDO_CREADO : 'Se creó el pedido correctamente',
    PEDIDO_MODIFICADO : 'Se modificó el pedido',
    PEDIDOS_CON_EL_CLIENTE : 'No se puede borrar el cliente porque hay pedidos que tienen el cliente especificado',
    PEDIDOS_CON_EL_PRODUCTO : 'No se puede borrar el producto porque hay pedidos que tienen el producto especificado',
    PEDIDOS_SIN_EL_CLIENTE : 'No hay pedidos que tengan el cliente especificado',
    PEDIDOS_SIN_EL_PRODUCTO : 'No hay pedidos que tengan el producto especificado',
    PEDIDOS_POR_PÁGINA : 'Pedidos por página',        
    PEDIDOS : 'Pedidos',
    PRODUCTO_ACTUALIZADO : 'Producto actualizado',
    PRODUCTO_INEXISTENTE : 'El producto especificado no existe',
    PRODUCTO_SIN_ESPECIFICAR : 'No se especifó un producto',
    VERIFICACION_OK : 'Pedido con datos correctos'
}

export {    
    constantes
};

