const constantes = {
    TITULO_APLICACION : 'Panes Negrita',
    ERROR : 'Error',
    // ERROR_CONEXION : 'Error al conectar con la BD',
    // ERROR_COMPROBAR_UNIDAD : 'Error al comprobar si existe la unidad',
    ERROR_GUARDAR_INGREDIENTE : 'Error al guardar el ingrediente',
    ERROR_BORRAR_INGREDIENTE : 'Error al borrar el ingrediente',
    // ERROR_BUSCAR_UNIDAD : 'Error al buscar una unidad',
    ERROR_LEER_INGREDIENTES : 'Error al leer los ingredientes',
    ERROR_CREAR_INDICE : 'Error al crear el índice',
    ERROR_ACTUALIZAR_INGREDIENTE : 'Error al actualizar el ingrediente',
    INGREDIENTES_SIN_LA_UNIDAD : 'No hay ingredientes con la unidad especificada',
    INGREDIENTES_CON_LA_UNIDAD : 'No se puede borrar la unidad porque hay ingredientes con la misma',
    // CONEXION_EXITOSA : 'Conexión exitosa',
    INGREDIENTES : 'Ingredientes',
    INGREDIENTES_POR_PAGINA: 'Ingredientes por página',
    INGREDIENTES_LEIDOS_CORRECTAMENTE: 'Ingredientes leidos correctamente',
    UNIDAD : 'Unidad',
    NOMBRE : 'Nombre del ingrediente',
    STOCK : 'Stock',
    STOCK_MINIMO : 'Stock mínimo',
    INGREDIENTE_EN_BLANCO : 'El nombre del ingrediente no puede estar en blanco',  
    INGREDIENTE_NULO : 'No se especificó un ingrediente',
    STOCK_INVALIDO : 'La cantidad en stock no puede ser negativa',    
    STOCK_MINIMO_INVALIDO : 'La cantidad mínima en stock no puede ser negativa ni mayor a la cantidad en stock',    
    UNIDAD_SIN_ESPECIFICAR : 'No se especificó una unidad para el ingrediente',    
    INGREDIENTE_REPETIDO : 'Ya existe un ingrediente con ese nombre',        
    INGREDIENTE_NO_REPETIDO : 'No existe un ingrediente con ese nombre',        
    INGREDIENTE_CREADO : 'Se creó el ingrediente correctamente',
    INGREDIENTE_MODIFICADO : 'Se modificó el ingrediente',
    INGREDIENTE_BORRADO : 'Se borró el ingrediente',
    NUEVO_INGREDIENTE : 'Nuevo Ingrediente',
    SIN_IMAGEN : '/subidas/Sin_imagen.jpg',
    MODIFICACION_INGREDIENTE : 'Modificación de ingrediente',
    BORRAR_INGREDIENTE : 'Borrar ingrediente',
    ACEPTAR : 'Aceptar',
    CANCELAR : 'Cancelar',
    MENSAJE_CONFIRMAR_BORRADO : '¿Confirma el borrado del ingrediente?',
    ESTADO_CON_STOCK : 'Con stock',
    ESTADO_CRITICO : 'Crítico',
    ESTADO_SIN_STOCK : 'Sin stock',
    ESTADO : 'Estado',
}

export {    
    constantes
};